spring:
  application:
    name: user-notes-backend
  main:
    banner-mode: off
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      path: "/h2"
      enabled: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION}